FROM ubuntu:latest

ENV TZ: Asia/Tokyo
RUN apt-get update \
      && apt-get install -y ruby \
      python \
      python3 \
      clang \
      gcc \
      g++ \
      golang \
      nodejs \
      lua5.3 \
      time \
      binutils \
      language-pack-ja-base language-pack-ja

ENV LANG=ja_JP.UTF-8
